### ISSUE TITLE
How to suspend on jetson nano

### ISSUE THREAD

**Issue by deandean82** [george-hawkins/pololu-romi-jetbot#1]
First of all,  I try the "sudo systemctl suspend" command, but I get Error like this "Failed to suspend system via logind: Sleep verb not supported"

In the datasheet I found that the pin 240 can control the system to sleep and wake up, but I don't know which pin on the pin240 corresponds to the board.And I guess pin 240 is the J40 pin1 , so I do the same experiment, but it just control the system poweroff and on, not the suspend.

Can you tell me how to suspend on jetson nano, Thanks

**Comment by george-hawkins** [comment]
As you already know that pin 240 is the SLEEP/WAKE pin I guess you've been looking at the [Jetson Nano datasheet](https://developer.nvidia.com/embedded/dlc/jetson-nano-datasheet).

And if you look at the [Jetson Nano developer kit user guide](https://developer.nvidia.com/embedded/dlc/jetson-nano-dev-kit-user-guide) you can see that _some_ of the power-related pins are broken out on the J40 header.

However, I think you're out of luck - the Jetson Nano module has a 260-pin SO-DIMM connector and only a small subset of these 260 pins are made available by the various headers and connectors on the development board. I don't think the SLEEP/WAKE pin is one of them.

I see you've already [asked about this](https://devtalk.nvidia.com/default/topic/1058352/jetson-nano/how-to-suspend-on-jetson-nano-/post/5366899) on the forums. I'd be interested to know if upgrading to Jetpack 4.2.1 (released in mid-July) changes the `systemctl` behavior you've seen. Like you, I'm currently running the older 4.2 release. However, even if this works it just means you can put the module into sleep mode - but will still not have access to a pin that enables you to wake it. For this, I think you'd need to design your own carrier board - a considerably more complicated task. But I could be wrong - if I were you, I'd ask a separate question regarding pin 240.

**Comment by deandean82** [comment]
I try "systemctl suspend" on the board, which is upgraded the jetpack 4.2.1.  the same error  "Failed to suspend system via logind: Sleep verb not supported". 
But modify /sys/power/state to "mem",  it seems working，and pull down J40 pin1 can wake it up. I think I need more experiments to prove this method is reliable.
